### ISSUE TITLE
ng serve compile problems

### ISSUE THREAD

**Issue by G33N** [AngularFirebase/65-contentful-angular#1]
Hi, I have this error on run `ng serve`
```
ERROR in TypeError: _this.host.getOutputName is not a function
    at getOriginalName (/Users/geen/Documents/GitHub/65-contentful-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:29588:32)
    at ReferenceTransformer.visitStringMap (/Users/geen/Documents/GitHub/65-contentful-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:29633:43)
    at visitValue (/Users/geen/Documents/GitHub/65-contentful-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:426:24)
    at /Users/geen/Documents/GitHub/65-contentful-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:483:65
    at Array.forEach (<anonymous>)
    at ReferenceTransformer.ValueTransformer.visitStringMap (/Users/geen/Documents/GitHub/65-contentful-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:483:26)
    at ReferenceTransformer.visitStringMap (/Users/geen/Documents/GitHub/65-contentful-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:29660:60)
    at visitValue (/Users/geen/Documents/GitHub/65-contentful-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:426:24)
    at /Users/geen/Documents/GitHub/65-contentful-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:483:65
    at Array.forEach (<anonymous>)
    at ReferenceTransformer.ValueTransformer.visitStringMap (/Users/geen/Documents/GitHub/65-contentful-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:483:26)
    at ReferenceTransformer.visitStringMap (/Users/geen/Documents/GitHub/65-contentful-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:29660:60)
    at visitValue (/Users/geen/Documents/GitHub/65-contentful-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:426:24)
    at /Users/geen/Documents/GitHub/65-contentful-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:483:65
    at Array.forEach (<anonymous>)
    at ReferenceTransformer.ValueTransformer.visitStringMap (/Users/geen/Documents/GitHub/65-contentful-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:483:26)
```

**Comment by helxsz** [comment]
I got the same problem. any idea?
